### ISSUE TITLE
Header Information appears in Body

### ISSUE THREAD

**Issue by schingeldi** [dunglas/DunglasAngularCsrfBundle#50]
I am using this great bundle with Symfony 2.7 and fos user bundle.

I started with this config:

```
dunglas_angular_csrf:
    # Collection of patterns where to set the cookie
    cookie:
        set_on:
            - { path: ^/$ }
            - { route: ^app_, methods: [GET, HEAD] }
            - { host: dev.local }
    # Collection of patterns to secure
    secure:
        - { path: ^/, methods: [POST, PUT, PATCH, LINK] }
#        - { route: ^ }
        - { host: dev.local, methods: [POST, PUT, PATCH, DELETE, LINK] }
```

I see the correct Response-Header.

However, when I return some json information, I get this in the Response Body as well:

Value: 98iTVMOTBYLfJXT1a70umTjsmMCpCZ7bKAmTXSuDwts, header: X-XSRF-TOKEN{"errors":{"email":"Email already exists"}}

So the Token is in the body and the header which breaks my JSON response.

Am I doing something wrong? I use this as an AJAX requet and in my Controller I do the following:

`return new JsonResponse(array('errors' => 
array('email' => $this->get('translator')->trans('registration.flash.user_email_exists', array(), 'user'))
), 400);`
dev.local is my test server I am working on.

Thanks for any help. Best regards
