### ISSUE TITLE
Problem with storing cookie in the browser

### ISSUE THREAD

**Issue by rvaliev** [dunglas/DunglasAngularCsrfBundle#53]
I can't get the cookie being stored in the browser cookie storage. However when I'm making a "GET" request I can see the cookie coming in the request header like this:

> Set-Cookie: XSRF-TOKEN=vtVV3OXgG4lE0qRBM6VvRuxry8P7jC71OP5dXE_smlQ; expires=Thu, 29-Mar-2018 05:43:23 GMT; Max-Age=360000; path=/; domain=angular-app.test

Here is my setup:

```
dunglas_angular_csrf:
    token:
        id: angular
    header:
        name: X-XSRF-TOKEN
    cookie:
        name: XSRF-TOKEN
        expire: 360000
        path: /
        secure: false
        domain: angular-app.test
        set_on:
            - { path: ^/$ }
            - { route: ^api_$, methods: [GET, HEAD] }
            - { host: symfony-app.test }
    secure:
        - { path: ^/api, methods: [POST, PUT, PATCH, LINK] }
        - { route: ^api$ }
        - { host: symfony-app.test, methods: [POST, PUT, PATCH, DELETE, LINK] }
```

Response headers:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://angular-app.test
Cache-Control: max-age=0, must-revalidate, private
Connection: keep-alive
Content-Type: application/json
Date: Sun, 25 Mar 2018 02:22:19 GMT
Server: nginx/1.11.8
Set-Cookie: XSRF-TOKEN=nYp_mhb5pVCNNf_-vsWOKMLf-_yB2lvdP5NOX-Rl5uc; expires=Thu, 29-Mar-2018 06:22:19 GMT; Max-Age=360000; path=/; domain=angular-app.test
Transfer-Encoding: chunked
```

I've also tried to add an extra dot to the domain like this:
`.domain: angular-app.test`

Angular app runs on: http://angular-app.test
Symfony app runs on: http://symfony-app.test

I'm also using a "nelmio/cors-bundle".

Any idea what it might be?
