### ISSUE TITLE
Config option to refresh token on every request

### ISSUE THREAD

**Issue by speto** [dunglas/DunglasAngularCsrfBundle#54]
Hello, what do you think about configuration option to refresh token on every request?

In configuration it could be something like:
```
dunglas_angular_csrf:
    token:
        # The CSRF token id
        id: angular
        refresh_every_request: true
```
And on this line it would be `refreshToken()` in that case:
https://github.com/dunglas/DunglasAngularCsrfBundle/blob/b2a9c4106f7ac36f5ed003ffeb7810d9b32addeb/EventListener/AngularCsrfCookieListener.php#L100
